# Generated by Django 4.0.5 on 2022-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='text',
        ),
        migrations.AlterField(
            model_name='ideas',
            name='idea',
            field=models.CharField(max_length=1024),
        ),
    ]
