# Generated by Django 4.0.5 on 2022-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_ideas_contributors_remove_ideas_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='idea',
            field=models.CharField(max_length=2048),
        ),
    ]
