# Generated by Django 4.0.5 on 2022-06-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_remove_user_followers_remove_user_follows_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Followers',
        ),
    ]
