# Generated by Django 4.0.5 on 2022-06-14 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_rename_follow_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followee',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
