# Generated by Django 4.0.5 on 2022-06-14 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_remove_followers_user_followers_followee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followee',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
