# Generated by Django 4.0.5 on 2022-06-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_remove_followers_user_followers_followee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followers',
        ),
    ]
