# Generated by Django 4.0.5 on 2022-06-16 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_user_followees_user_followers_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='agreers',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='disagreers',
        ),
        migrations.AddField(
            model_name='ideas',
            name='bright',
            field=models.ManyToManyField(blank=True, related_name='bright', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideas',
            name='dark',
            field=models.ManyToManyField(blank=True, related_name='dark', to=settings.AUTH_USER_MODEL),
        ),
    ]
